### ISSUE TITLE
Add Support for Compact mode (js-Controller 2.0 Feature)

### ISSUE THREAD

**Issue by ldittmar81** [SwedishChef/ioBroker.bosesoundtouch#28]
The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

**Comment by SwedishChef1** [comment]
The instructions mentioned in the link are for functional implemented adapters (like the template). BoseSoundtouch adapter is implemented in an object oriented approach and therefore I would need some assistance how this could look like in this case. I'm still a Javascript newbie ;-)

Many thanks.

**Comment by jogibear9988** [comment]
look at my adapter, i've also used ES6 classes https://github.com/iobroker-community-adapters/ioBroker.oilfox

**Comment by jogibear9988** [comment]
and also, maybe you want to join us: https://github.com/iobroker-community-adapters/info/blob/master/ABOUT_US.md

**Comment by SwedishChef** [comment]
Lastest version 0.9.1 should support compact mode but I failed to test it. Any feedback on this issue is highly welcome. If something is missing or does not work, please re-open that issue.
