### ISSUE TITLE
Update Stable with 0.9.2 !!

### ISSUE THREAD

**Issue by Apollon77** [SwedishChef/ioBroker.bosesoundtouch#41]
to support js.controller 3 release!

**Comment by cavernerg** [comment]
0.9.2 isn't stable - support for zones is missing, which is working in 0.2.4

**Comment by SwedishChef** [comment]
> 0.9.2 isn't stable - support for zones is missing, which is working in 0.2.4

could you please check with 0.9.3 - thx

**Comment by cavernerg** [comment]
0.9.3 seems to be pretty good! thanks

**Comment by SwedishChef** [comment]
new stable version: 0.9.3
