### ISSUE TITLE
Radio stations are not accepted

### ISSUE THREAD

**Issue by ipod86** [SwedishChef/ioBroker.bosesoundtouch#45]
I saw the adapter by accident and was very happy.

However, I have a problem.

If I enter "PRESET_1" under "key", 90% of the entries are not accepted and no radio station is changed.

At some point it takes an input, but then comes a radio station from another preset.

However, the "POWER" command is always accepted via the "key" field. "Volume" and "on" also work.

Bose Soundtouch 10
Node.js V10.21.0

**Comment by ipod86** [comment]
Edit:

I have now discovered why it does not switch.  By sending the presets, they are deleted on the Bose.

**Comment by ipod86** [comment]
I tested it further.  With "preset" he moves and deletes stations.  I have the feeling that it deletes the currently running radio station from the preset and moves it to the newly selected position.

**Comment by SwedishChef** [comment]
fixed with 0.9.3
