### ISSUE TITLE
Multi Zone Support

### ISSUE THREAD

**Issue by sven-s-ter** [SwedishChef/ioBroker.bosesoundtouch#50]
MultiZone is actually not working. Is there any Plan to fix it? 
Even when same music is played no zone is or can be set up. Thx

**Comment by SwedishChef** [comment]
could you please retest with 0.9.3 - thx

**Comment by sven-s-ter** [comment]
> could you please retest with 0.9.3 - thx

Shure. Broker Shows latest Version 0.9.2. (latest repos) Where can i find it?

**Comment by SwedishChef** [comment]
>... Where can i find it?

please download from github and install manually. 'npm publish' does not work at the moment for me. working on that...

**Comment by SwedishChef** [comment]
works with new stable version 0.9.3
